image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - main
  script:
    - apk add --no-cache docker-compose make ansible
    - make test


deploy:
  stage: deploy
  environment:
    name: production
  only:
    - main
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  before_script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY_DEPLOY}" | tr -d '\r' | ssh-add - > /dev/null
    - echo "${ANSIBLE_PASSWORD}" > compose/.ansible-vault-password.txt
  script:
    - apk add --no-cache docker-compose make ansible
    - make build
    - cd compose && ansible-playbook -i hosts.yml deploy.yml --limit production -e @vars/production.yml --vault-password-file .ansible-vault-password.txt
  artifacts:
    paths:
      - bin/app
    expire_in: 7 days
