version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/opt/swagger.json
    volumes:
      - ./docs/swagger.json:/opt/swagger.json
