---
all:
  hosts:
    local:
      connection: local
      ansible_connection: local
      ansible_user: "{{ lookup('env', 'USER') }}"

    production:
      ansible_host: "{{ ANSIBLE_HOST }}"
      ansible_user: "{{ ANSIBLE_USER }}"
      ansible_sudo_pass: "{{ ANSIBLE_SUDO_PASS }}"
